spring.application.name=DAY27_STS_SPRING_DATA_REST-CRUD
server.servlet.context-path=/product
spring.datasource.url=jdbc:mysql://localhost/flm
spring.datasource.username=root
spring.datasource.password=Naiduking@123
spring.jpa.hibernate.ddl-auto=update