spring.application.name=SPRING_SECURITY
server.port=9091
server.servlet.context-path=/sample
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp
spring.security.user.name=vinnu
spring.security.user.password=welcome
