spring.application.name=DAY28_STS_MICROSERVICES_CRUD
server.servlet.context-path=/department
spring.datasource.url=jdbc:mysql://localhost/flm-department
spring.datasource.username=root
spring.datasource.password=Naiduking@123
spring.jpa.hibernate.ddl-auto=update
server.port=8080