spring.application.name=SPRING_SECURITY01
server.servlet.context-path=/sample
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp
spring.security.user.name=vinni
spring.security.user.password=welcome

