spring.application.name=DAY25_STS_SPRING_DATA_WEB_CRUD_QUERY
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp
server.servlet.context-path=/employee
spring.datasource.url=jdbc:mysql://localhost/flm
spring.datasource.username=root
spring.datasource.password=Naiduking@123
spring.jpa.hibernate.ddl-auto=update