spring.application.name=DAY22_STS_SPRINGBOOT_WEB_MVC
spring.mvc.view.prefix=/WEB-INF/pages/
spring.mvc.view.suffix=.jsp
server.servlet.context-path=/employee
spring.datasource.url=jdbc:mysql://localhost/flm
spring.datasource.username=root
spring.datasource.password=Naiduking@123